# Generated by Django 4.2.7 on 2023-12-25 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("genre", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "bookid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("isbn", models.CharField(max_length=50)),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Updated At"),
                ),
                ("rating", models.IntegerField(default=0, verbose_name="Rating")),
                ("publishyear", models.DateField(verbose_name="Year Of Publish")),
                (
                    "avaliablecopies",
                    models.IntegerField(verbose_name="Avaliable Copies"),
                ),
                ("noofreviews", models.IntegerField(verbose_name="No of Reviews")),
                ("bookpages", models.IntegerField(verbose_name="Number Of Book Pages")),
                (
                    "author",
                    models.ManyToManyField(
                        to="account.authoruser", verbose_name="Author"
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(to="genre.genre", verbose_name="Genre"),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "transactionid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Transaction ID",
                    ),
                ),
                ("checkoutdate", models.DateField(verbose_name="Checkout Date")),
                ("returndate", models.DateField(verbose_name="Return Date")),
                (
                    "finepaid",
                    models.BooleanField(default=False, verbose_name="Fine Paid"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("C", "Checked Out"),
                            ("R", "Returned"),
                            ("L", "Lost"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Updated At"),
                ),
                (
                    "bookid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.book",
                        verbose_name="Book ID",
                    ),
                ),
                (
                    "patronid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.patronuser",
                        verbose_name="Patron ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transactions",
                "verbose_name_plural": "Transactionss",
            },
        ),
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "reviewid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Review ID",
                    ),
                ),
                ("rating", models.IntegerField(verbose_name="Rating")),
                ("comment", models.TextField(verbose_name="Commment")),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Updated At"),
                ),
                (
                    "bookid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.book",
                        verbose_name="Book ID",
                    ),
                ),
                (
                    "patronid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.patronuser",
                        verbose_name="Patron ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reviews",
                "verbose_name_plural": "Reviewss",
            },
        ),
        migrations.CreateModel(
            name="BookStatus",
            fields=[
                (
                    "bookstatusid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Book Status ID",
                    ),
                ),
                (
                    "totalpages",
                    models.IntegerField(verbose_name="Total Number Of Pages"),
                ),
                (
                    "presentpage",
                    models.IntegerField(default=0, verbose_name="Present Page"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("R", "read"), ("I", "Incomplete"), ("U", "unread")],
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "bookid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.book",
                        verbose_name="Book ID",
                    ),
                ),
                (
                    "customuser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Patron ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "BookStatus",
                "verbose_name_plural": "BookStatuss",
            },
        ),
    ]
