# Generated by Django 4.2.7 on 2023-12-25 20:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "genreid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Genre ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Genre Name")),
                ("description", models.TextField(verbose_name="Description")),
            ],
            options={
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
            },
        ),
    ]
